sudo: required
services:
    - docker

before_install:
    - docker build -t juozasa/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true juozasa/docker-react npm run test -- --coverage